
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-deployment
  labels:
    deployment: bolado_deployment
spec:
  selector:
    matchLabels:
      example: olx-bolada
  template:
    metadata:
      labels:
        example: olx-bolada
    spec:
      containers:
      - name: meu-container
        image: ralphavalon/kube_features:v2
        ports:
        - containerPort: 8081
        env:
        - name: API_HOST
          value: "192.168.99.100:30934"
        - name: SECRET_DB_HOST
          value: "10.98.170.237"
        - name: SECRET_DB_USER
          valueFrom:
            secretKeyRef:
              name: meu-secret
              key: username
        - name: SECRET_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: meu-secret
              key: password
        - name: SECRET_DB_PORT
          value: "5432"
        - name: SECRET_DB_NAME
          value: "bolado_db"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
