apiVersion: v1
kind: Service
metadata:
    name: meu-service
    labels:
        service: olx-bolada-service
spec:
    type: NodePort
    ports:
    - port: 8081
    selector:
        example: olx-bolada
