
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-deployment-v1
  labels:
    deployment: bolado_deployment_v1
spec:
  selector:
    matchLabels:
      example: olx-bolada-v1
  template:
    metadata:
      labels:
        example: olx-bolada-v1
    spec:
      containers:
      - name: meu-container-v1
        image: ralphavalon/kube_features:v1
        ports:
        - containerPort: 8081
        env:
        - name: API_HOST
          value: "192.168.99.100:30388"
        - name: EXTERNAL_API
          value: "http://meu-service:8081"
          # value: "http://meu-service.default.svc.cluster.local:8081"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
